"""Create Repo, Dependency and RepoDependency tables

Revision ID: 0232d84a5aea
Revises:
Create Date: 2023-08-02 22:14:12.910175

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0232d84a5aea"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dependency",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "repo",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("stars", sa.BigInteger(), nullable=False),
        sa.Column("source_graph_repo_id", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_graph_repo_id"),
        sa.UniqueConstraint("url"),
    )
    op.create_table(
        "repo_dependency",
        sa.Column("repo_id", sa.Integer(), nullable=False),
        sa.Column("dependency_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dependency_id"], ["dependency.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["repo_id"], ["repo.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("repo_id", "dependency_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("repo_dependency")
    op.drop_table("repo")
    op.drop_table("dependency")
    # ### end Alembic commands ###
